aa: None
adv_training: pgd
attack: pgd
attack_boundaries:
- 0
- 1
attack_eps: 4
attack_lr: null
attack_norm: linf
attack_steps: 1
amp: false
aug_splits: 0
batch_size: 64
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 10
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data_dir: gs://large-ds/tensorflow_datasets
dataset: tfds/imagenet2012:5.1.0
decay_epochs: 100
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.05
epoch_repeats: 0.0
epochs: 100
eps_schedule: linear
eps_schedule_period: 10
eval_metric: robust_top1
experiment: xcit
force_cpu: false
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: 5.0e-4
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: xcit_small_12_p16_224
model_ema: false
model_ema_decay: 0.99996
momentum: 0.9
no_aug: false
no_normalize: true
no_resume_opt: false
num_classes: null
opt: adamw
opt_betas: null
opt_eps: 1.0e-8
output: gs://robust-vits/
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: bicubic
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 10
warmup_lr: 1.0e-6
weight_decay: 0.5
workers: 4
